default:
  BOT_TOKEN: secret
  DEBUG: true
  FORBIDDEN_WORDS: secret
  BIRTHDAYS: secret
  CHAT_ID: secret
  WEATHER_APIKEY: secret
  OPENAI_APIKEY: secret

development:
  DEBUG: true

heroku:
  DEBUG: false